[package]
name = "cli"
version = "0.1.0"
authors = ["shivshank"]
edition = "2018"

[dependencies]
clap = "2.32.0"
tera = "0.11.8"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
pulldown-cmark = "0.2.0"
